name: Cleanup
on:
  workflow_run:
    workflows: ["test-build"]
    types:
      - completed

jobs:
  build-and-cache:
    #TODO model dependency to image-workflow. Workaround: retrigger run after image-workflow finished.
    runs-on: intellabs-01
    steps:
      - name: Build
        shell: bash
        run: |
          ls -l 